version: 1
update_configs:
- package_manager: java:maven
  directory: /
  update_schedule: daily
  automerged_updates:
  - match:
      dependency_type: all
      update_type: semver:minor
  commit_message:
    prefix: fix
    prefix_development: chore
    include_scope: true
- package_manager: javascript
  directory: /
  update_schedule: daily
  automerged_updates:
  - match:
      dependency_type: all
      update_type: semver:minor
  commit_message:
    prefix: fix
    prefix_development: chore
    include_scope: true
